version: '3'
services:
  catalog:
    build: ./catalog
    ports:
      - "5000:5000"
    volumes:
      - ./catalog/catalog.json:/app/catalog.json
    networks:
      - book-network

  catalog-replica:
    build: ./catalog
    ports:
      - "5004:5000"  # host:container
    volumes:
      - ./catalog/catalog.json:/app/catalog.json
    networks:
      - book-network

  order:
    build: ./order
    depends_on:
      - catalog
    ports:
      - "5001:5001"
    volumes:
      - ./order/orders.json:/app/orders.json
    networks:
      - book-network

  order-replica:
    build: ./order
    depends_on:
      - catalog
    ports:
      - "5003:5001"
    volumes:
      - ./order/orders.json:/app/orders.json
    networks:
      - book-network

  frontend:
    build: ./frontend
    depends_on:
      - order
      - order-replica
      - catalog
      - catalog-replica
    ports:
      - "5002:5002"
    networks:
      - book-network

networks:
  book-network:
    driver: bridge
